# Generated by Django 6.0.4 on 2026-04-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('participants', models.JSONField(default=list)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('cc', models.JSONField(default=list)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('direction', models.CharField(choices=[('incoming', 'Reçu'), ('outgoing', 'Envoyé')], default='incoming', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'Haute'), ('normal', 'Normale'), ('low', 'Basse')], default='normal', max_length=20)),
                ('category', models.CharField(choices=[('action_required', 'Action requise'), ('waiting_reply', 'En attente de réponse'), ('informational', 'Informatif'), ('spam', 'Spam'), ('newsletter', 'Newsletter'), ('other', 'Autre')], default='other', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('action_detected', models.BooleanField(default=False)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('needs_reply', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailthread')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='emails.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
